TASKS = {
    "easy": {
        "num_machines": 2,
        "num_jobs": 3,
        "failures": False,
        "failure_rate": 0.0,
        "max_priority": 1,
        "job_time_range": (2, 5),
        "deadline_slack": (4, 8),
        "max_steps": 20,
        "description": "Assign 3 jobs to 2 machines with no failures.",
    },
    "medium": {
        "num_machines": 4,
        "num_jobs": 7,
        "failures": True,
        "failure_rate": 0.08,
        "max_priority": 2,
        "job_time_range": (3, 7),
        "deadline_slack": (2, 5),
        "max_steps": 30,
        "description": "Manage 7 jobs across 4 machines with random breakdowns.",
    },
    "hard": {
        "num_machines": 6,
        "num_jobs": 12,
        "failures": True,
        "failure_rate": 0.15,
        "max_priority": 3,
        "job_time_range": (3, 8),
        "deadline_slack": (1, 4),
        "max_steps": 40,
        "description": "Optimize throughput across 12 jobs and 6 machines under frequent failures.",
    },
}
